run.app <-
function(app.name) {
  if(missing(app.name)) {
    mcat("Available Apps:")
    mcat("----------------------------------")
    mcat("Bias vs Variance - bias-variance")    
    mcat("Simple Random Sample vs Stratified Sampling - sampling")
    mcat("Construct a Frequency Table and Histogram - histogram")
    mcat("Mean or Median? - meanmedian")
    mcat("Calculate a Standard Deviation = standdev")
    mcat("Empirical Rule = emprule")
    mcat("Finding Percentiles = percentile")    
    mcat("Drawing a Boxplot = boxplot")
    mcat("The Geometric Distribution = geometric")
    mcat("Illustrates Different Probability Distributions = distributions")    
    mcat("The Normal Distribution = normal")
    mcat("Probabilities under the Normal Curve = normalprob")    
    mcat("Central Limit Theorem = clt")
    mcat("Illustration of the Meaning of a Confidence Interval = confint")
    mcat("Introduction to the ideas of Hypothesis Testing via Coin toss = coin")    
    mcat("Illustration of the concept of p Value = pvalue")
    mcat("Random Problem Generator for Statistical Inference = infproblems")
    mcat("Illustration of the concept of Power of a Test = power")    
    mcat("Illustration of the concept of Power of a Test using Proportions = powerProp")
    mcat("Illustration of the concept of Power of a Test using the Mean = powerMean")
    mcat("Illustration of the Meaning of the Correlation Coefficient = correlation")
    mcat("Illustration of Least Squares Regression I = lsr")
    mcat("Illustration of Least Squares Regression II = lsr1")
    mcat("Illustration of Least Squares Regression III = lsr2")        
    mcat("Calculations for the Correlation Coefficient and of Least Squares Regression = corcalc")
    mcat("Assumptions of Least Squares Regression = assumptionsLSR")
    mcat("Chisquare anlysis of a 2x2 table = 2_2_table")
    mcat("Illustration of the Idea behind Analysis of Variance = anova")
    mcat("Twosample t Test = twosample")
    mcat("Transformations = transformations")
    mcat("Polynomial Regression = polyreg")
    mcat("Illustration of Derivatives = derivative")
    mcat("Taylor Approximations = taylor")
    mcat("Approximating an Integral by Riemann Sums = integral")
    mcat("Illustration of Several Numerical Integration Methods = numint")  
    mcat("Random Walk in 1, 2 or 3 Dimensions = rw")
    mcat("----------------------------------")
    app.name <- readline("Type the name of the App you want to run, then hit enter:  ")
  }
  else 
    app.name <- deparse(substitute(app.name))
  runUrl(paste0("http://academic.uprm.edu/wrolke/shiny/", app.name, ".zip"))

}
